name: myActions1
run-name: ${{ github.actor }} is learning GitHub Actions and workflows
on: [push]
jobs:
  action1job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout
      - name: build code
        run: |
          cd src
          make clean
          make

